from db  import db

class	ItemModel(db.Model):

	__tablename__ = 'items'
	
	id 		= 	db.Column(db.Integer, primary_key=True)
	name 		= 	db.Column(db.String(80))
	price		= 	db.Column(db.Float(precision=2))
	storeid 	= 	db.Column(db.Integer, db.ForeignKey('stores.id'))
	store		=	db.relationship('StoreModel')

	def	__init__(self, name, price, storeid):
		# id is autogenerated by sqlalchemy
		self.name 		=	name
		self.price 		=	price
		self.storeid	=	storeid
		
	def	json(self):
		return	{'name': self.name, 'price': self.price, 'storeid': self.storeid}

	@classmethod
	def	find_by_name(cls, name):	
		return	cls.query.filter_by(name=name).first()
				
	def	save_to_db(self):
		db.session.add(self)
		db.session.commit()
		
	def	delete_from_db(self):
		db.session.delete(self)
		db.sesion.commit()
		
	@classmethod
	def	get_all(cls):
		return	cls.query.all()
	
	@classmethod	
	def	get_all_as_json(cls):
		return	[item.json() for item in cls.get_all()]

		